# Generated by Django 3.0.4 on 2020-03-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listlink',
            old_name='user',
            new_name='avtor',
        ),
    ]
