# Generated by Django 3.0.4 on 2020-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0002_auto_20200327_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listlink',
            name='long_link',
            field=models.URLField(max_length=250, unique=True, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='listlink',
            name='short_link',
            field=models.CharField(max_length=100, verbose_name='Короткая ссылка'),
        ),
    ]
