# Generated by Django 3.0.4 on 2020-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0003_auto_20200328_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listlink',
            name='long_link',
            field=models.URLField(max_length=250, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='listlink',
            name='short_link',
            field=models.CharField(max_length=100, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
